services:
  backend:
    profiles: [ "site" ]
    container_name: backend
    build: ./backend/
    # ports:
    #   - "8000:8000"
    environment:
      DB__USER: root
      DB__PASSWORD: ${DATA_MYSQL_PASSWORD}
      DB__HOST: my-mysql
      DB__PORT: 3306
      DB__NAME: app
      APP__PORT: 8000
      APP__FRONTEND_URL: http://frontend:80
    depends_on:
      my-mysql:
        condition: service_healthy

  # frontend:
  #   profiles: [ "site" ]
  #   container_name: frontend
  #   build: ./frontend/
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   environment:
  #     CHOKIDAR_USEPOLLING: true
  #     WATCHPACK_POLLING: true
  #     VITE_BACKEND_URL: http://backend:8000

  frontend:               # ← теперь это nginx + статика
    profiles: ["site"]
    container_name: frontend
    build:
      context: ./frontend
      target: production   # или просто убрать target, если Dockerfile заканчивается на production-stage
    ports:
      - "80:80"            # или 8080:80, 443:443 и т.д.
    depends_on:
      - backend

  my-mysql:
    image: mysql:8.0.16
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATA_MYSQL_PASSWORD}
      MYSQL_DATABASE: app
    ports:
      - "3307:3306"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d/
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysql", "-uroot", "-p${DATA_MYSQL_PASSWORD}", "-e", "USE app; SELECT 1;"]
      timeout: 30s
      retries: 10
      interval: 10s
      start_period: 40s

  data-loader:
    profiles: [ "data-loader" ]
    container_name: data-loader
    build: ./data-loader/
    environment:
      DATABASE_URL: mysql+pymysql://root:${DATA_MYSQL_PASSWORD}@my-mysql:3306/app
      LOGGING_LEVEL: INFO
    depends_on:
      my-mysql:
        condition: service_healthy

  metaphone:
    profiles: [ "deduplicator" ]
    container_name: metaphone
    build: ./deduplicator/
    environment:
      DATABASE_URL: mysql+pymysql://root:${DATA_MYSQL_PASSWORD}@my-mysql:3306/app
      MODE: metaphone
    depends_on:
      my-mysql:
        condition: service_healthy
      clear:
        condition: service_completed_successfully

  clear:
    profiles: [ "deduplicator" ]
    container_name: clear
    build: ./deduplicator/
    environment:
      DATABASE_URL: mysql+pymysql://root:${DATA_MYSQL_PASSWORD}@my-mysql:3306/app
      MODE: clear
    depends_on:
      my-mysql:
        condition: service_healthy

  deduplicate:
    profiles: [ "deduplicator" ]
    container_name: deduplicate
    build: ./deduplicator/
    environment:
      DATABASE_URL: mysql+pymysql://root:${DATA_MYSQL_PASSWORD}@my-mysql:3306/app
      MODE: deduplicate
    depends_on:
      my-mysql:
        condition: service_healthy
      clear:
        condition: service_completed_successfully
      metaphone:
        condition: service_completed_successfully

volumes:
  mysql_data:
  frontend-dist:
