services:
  backend:
    container_name: book-backend
    build: ./backend/
    ports:
      - "8000:8000"
    environment:
      DB__USER: root
      DB__PASSWORD: ${DATA_MYSQL_PASSWORD}
      DB__HOST: my-mysql
      DB__PORT: 3306
      DB__NAME: app
      APP__PORT: 8000
      APP__FRONTEND_URL: http://frontend:5173

  frontend:
    container_name: book-frontend
    build: ./frontend/
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
      VITE_BACKEND_URL: http://backend:8000

  my-mysql:
    build: ./my-mysql/
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATA_MYSQL_PASSWORD}
      MYSQL_DATABASE: app
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DATA_MYSQL_PASSWORD}" ]
      timeout: 30s
      retries: 10
      interval: 10s
      start_period: 40s

  data-pipeline:
    profiles: [ "data-pipeline" ]
    container_name: data-pipeline
    build: ./data_pipeline/
    environment:
      DATABASE_URL: mysql+pymysql://root:${DATA_MYSQL_PASSWORD}@my-mysql:3306/app
      LOGGING_LEVEL: INFO
    depends_on:
      my-mysql:
        condition: service_healthy

  metaphone:
    profiles: [ "deduplicator" ]
    container_name: metaphone
    build: ./deduplicator/
    environment:
      DATABASE_URL: mysql+pymysql://root:${DATA_MYSQL_PASSWORD}@my-mysql:3306/app
      MODE: metaphone
    depends_on:
      my-mysql:
        condition: service_healthy

  clear:
    profiles: [ "deduplicator" ]
    container_name: clear
    build: ./deduplicator/
    environment:
      DATABASE_URL: mysql+pymysql://root:${DATA_MYSQL_PASSWORD}@my-mysql:3306/app
      MODE: clear
    depends_on:
      my-mysql:
        condition: service_healthy


volumes:
  mysql_data:
